_posts/2022-03-20-5-modulos-uteis-para-seu-dia-a-dia-como-SRE.markdown

First post test

---

_posts/2022-03-19-Incident-Analysis-101-Facilitating-the-Learning-Review.markdown
index.markdown

prep da edição 2

---

index.markdown

Atualizar headline do index da Edição #2

Atualizar headline do index da Edição #2

---

_posts/2022-03-21-On-the-Brittleness-of-Dashboards.markdown

Edição #2 - 21.03.2022 | https://www.honeycomb.io/blog/brittleness-of-dashboards/

---

_posts/2022-03-21-when-to-hire-an-incident-commander.markdown

Quando contratar um IC (Incident Commander)

Edição #2 - 21.03.2022 | https://firehydrant.io/blog/when-to-hire-an-incident-commander/

---

_posts/2022-03-21-What-Does-AIOps-Mean-for-SREs.markdown

PR issue26 - O que AIOps representa para engenheiros de confiabilidade?

Edição #2 - 21.03.2022 | https://rootly.com/blog/what-does-aiops-mean-for-sres-it-s-complicated

---

anteriores.md
edicao2.md

Atualizar index para Edição #3

---

_posts/2022-03-28-Apply-these-FinOps-best-practices-to-optimize-cloud-costs.markdown

Artigo: FinOps: Princípios e práticas para otimizar custos na cloud

Revisar | https://www.techtarget.com/searchcloudcomputing/tip/Apply-these-FinOps-best-practices-to-optimize-cloud-costs

---

_posts/2022-03-28-who-watches-the-watchers.markdown

Artigo: Quem monitora a monitoração?

Revisar | https://engineering.nanit.com/who-watches-the-watchers-1608d29ac3a8

---

anteriores.md
edicao3.md

Preparar index da edição #4

---

_posts/2022-04-04-Team-Topologies-Organizing-Business-Technology.markdown

Revisar | Team Topologies: Organizing Business and Technology Teams for Fast Flow (English Edition)

Revisar | Team Topologies: Organizing Business and Technology Teams for Fast Flow (English Edition)

---

_posts/2022-04-04-circuit-breakers.markdown

Revisar | https://www.infoq.com/articles/mtt-metrics-incident-response/

Revisar | https://www.infoq.com/articles/mtt-metrics-incident-response/

---

_posts/2022-04-04-mtt-metrics-incident-response.markdown

Revisar | https://brooker.co.za/blog/2022/02/16/circuit-breakers.html

Revisar | https://brooker.co.za/blog/2022/02/16/circuit-breakers.html

---

anteriores.md
edicao3.md

Atualizar index para Edição #4

Atualizar index para Edição #4

---

_posts/2022-04-04-mtt-metrics-incident-response.markdown

Fix MTT* JSON parsing error

---

.vscode/settings.json
_posts/2022-04-04-Team-Topologies-Organizing-Business-Technology.markdown
_posts/2022-04-04-circuit-breakers.markdown
_posts/2022-04-04-mtt-metrics-incident-response.markdown

Corrigir ordem dos headlines e titulos de highlight da Edição #4

---

_posts/2022-04-10-how-disaster-ready-are-your-backup-systems-really.markdown

Revisar | https://www.blameless.com/sre/how-disaster-ready-are-your-backup-systems-really

---

_posts/2022-04-10-spike-detection-in-alert-correlation.markdown

Revisar | https://engineering.linkedin.com/blog/2021/spike-detection-in-alert-correlation

---

_posts/2022-04-10-sre-teams-more-than-technical-problem-solvers.markdown

Revisar | https://www.rtinsights.com/sre-teams-more-than-technical-problem-solvers/

---

anteriores.md
edicao4.md

Preparar Index da Edição #5

---

index.markdown

Fix header da Edição #5

---

_posts/2022-04-17-the-essencial-guide-to-sre.markdown

Revisar | The essential Guide to SRE da Blameless

---

_posts/2022-04-17-observability-power-of-asking-questions.markdown

Revisar | https://www.honeycomb.io/blog/observability-power-of-asking-questions/

---

_posts/2022-04-17-how-to-utilize-the-power-of-aiops-for-improved-observability.markdown

Revisar | https://www.forbes.com/sites/forbestechcouncil/2022/04/07/how-to-utilize-the-power-of-aiops-for-improved-observability/?sh=5704f8322283

---

anteriores.md
edicao5.md

Preparar index da Edição 6

---

_posts/2022-04-17-the-essencial-guide-to-sre.markdown

fix blameless

---

_posts/2022-04-24-sre-vs-platform-engineering-whats-the-difference.markdown

Revisar | https://devops.com/sre-vs-platform-engineering-whats-the-difference/

---

_posts/2022-04-24-in-criminalizing-error-we-are-doomed-to-repeat-our-mistakes.markdown

Revisar | https://www.thenation.com/article/society/accidental-death-radonda-vaught/

---

_posts/2022-04-24-the-pros-and-cons-of-embedded-sres.markdown

Revisar | https://rootly.com/blog/the-pros-and-cons-of-embedded-sres?utm_source=dzone&utm_medium=blog

---

anteriores.md
edicao6.md

Atualizar Index da Edição #7

---

_posts/2022-04-29-incident-analysis-101-handling-action-items.markdown

Revisar | https://www.jeli.io/blog/incident-analysis-101-handling-action-items/

---

_posts/2022-04-29-incident-analysis-101-handling-action-items.markdown

Consertar titulo

---

_posts/2022-05-08-8-reasons-site-reliability-engineer-one-most-demand-jobs-2022.markdown

Revisar | https://enterprisersproject.com/article/2022/2/8-reasons-site-reliability-engineer-one-most-demand-jobs-2022

---

_posts/2022-05-08-automating-sre-to-scale-operations.markdown

Revisar | https://www.toolbox.com/tech/devops/articles/automating-sre-to-scale-operations/

---

_posts/2022-05-16-devops-cloud-security.markdown

Revisar | https://www.infoq.com/articles/devops-cloud-security/

---

_posts/2022-05-16-anatomia-dos-servicos-de-cloud-e-como-eles-aceleram-inovacao.markdown

Revisar | https://www.linkedin.com/pulse/anatomia-dos-servi%25C3%25A7os-de-cloud-e-como-eles-aceleram-coelho-de-sousa/

---

_posts/2022-05-16-give-me-back-my-monolith.markdown

2022-05-16-give-me-back-my-monolith.markdown

---

edicao10.md
edicao11.md

Preparar pagina da edição 11

---

_posts/2022-05-29-how-we-deploy-to-production-over-100-times-a-day.markdown

Revisar | https://monzo.com/blog/2022/05/16/how-we-deploy-to-production-over-100-times-a-day

---

_posts/2022-05-29-srecon22americas-presentation-stanke.markdown

Revisar | https://www.usenix.org/system/files/sre22amer_slides_stanke.pdf

---

_posts/2022-06-05-metrics-driven-prioritization-for-your-reliability-roadmap.markdown

Revisar | https://www.usenix.org/system/files/sre22amer_slides_tan.pdf

---

_posts/2022-06-05-can-sre-bring-governance-and-compliance-into-the-future.markdown

Revisar | https://thenewstack.io/can-sre-bring-governance-and-compliance-into-the-future/

---

_posts/2022-06-05-the-need-to-decouple-human-error-from-incident-response.markdown

Revisar | https://thenewstack.io/the-need-to-decouple-human-error-from-incident-response/

---

_posts/2022-06-09-dummy2.markdown

testar yaml lint

---

.gitignore
_posts/2022-06-13-readiness-to-learn-safely-and-reliably-deploy-to-the-cloud.markdown
_posts/2022-06-13-the-cyber-incident-response-plan-the-power-is-in-the-process.markdown
_posts/2022-06-13-why-you-need-chaos-engineering.markdown

why-you-need-chaos-engineering

---

Gemfile
Gemfile.lock
_config.yml

Primeira atualização do novo tema

Novo tema para o SREBrasilNoticias

---

_posts/2022-06-18-incident-response-incident-priority-matrix copy.markdown
_posts/2022-06-18-starting-an-sre-team-from-scratch-quick-guide.markdown
_posts/2022-06-18-what-is-an-sre-product-manager copy.markdown

PR dos artigos da edição 15

---

.github/workflows/docker-build.yml
_posts/2022-06-27-why-the-full-stack-engineer-is-problematic.markdown

Fix yaml on article

---

docker-compose.yml

Atualização do Docker-compose

---

Deployment.yaml

teste new docker build

---

_includes/navigation.html
_posts/2022-07-04-devops-is-a-failure.markdown
_posts/2022-07-04-multiwindow-multi-burn-rate-alerts.markdown
_posts/2022-07-07-keep-calm-and-use-the-runbook.markdown
edicao18.md

Fechar Release 18

---

_includes/navigation.html
edicao19.md

Publicar Release #19

---

_includes/navigation.html
edicao20.md

Publicar release #20

---

.github/workflows/blogposts.yml
README.md

Update do README a partir do feed do SREBrasil Noticias

---

_posts/2022-08-15-is-sre-just-ops-with-a-new-name.markdown
_posts/2022-08-15-no-observability-without-theory.markdown
_posts/2022-08-15-why-observability-is-shifting-left.markdown

fix bug with yaml na release #23

---

_posts/2022-10-09-qual-o-papel-do-sre-em-um-mundo-lownowcode.markdown

Fix 2022-10-09-qual-o-papel-do-sre-em-um-mundo-lownowcode.markdown

Fix 2022-10-09-qual-o-papel-do-sre-em-um-mundo-lownowcode.markdown

---

_posts/2022-10-09-qual-o-papel-do-sre-em-um-mundo-lownowcode.markdown

Correção de erro ortográfico
